
namespace xBDD
{
	using System;
	using System.Text;
	using xBDD.Utility;
	/// <summary>
	/// Tracks one or more tags for the scenario or feature.
	/// This is generated by the xBDD code writer.  Do Not use this attribute in your code.
	/// </summary>
	[System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Method, AllowMultiple = true)]
	public class Generated_TagsAttribute : System.Attribute
	{
		string[] tags;
			
		/// <summary>
		/// Tracks one or more tags for the scenario or feature.
		/// This is generated by the xBDD code writer.  Do Not use this attribute in your code.
		/// </summary>
		/// <param name="tags">The tags for the scenario or feature.</param>
		public Generated_TagsAttribute(params string[] tags)
		{
			this.tags = tags;
		}
	
		/// <summary>
		/// Returns a string array of tags.
		/// </summary>
		/// <returns>The names of the tags.</returns>
		public string[] GetTags()
		{
			return tags;
		}
	}
}
